### ISSUE TITLE
Sensitivity analysis optimisation

### ISSUE THREAD

**Issue by BalancedmonkeY** [CRSU-Apps/MetaInsight#18]
Other than the Bayesian tab, when a user ticks a study to be removed for a sensitivity analysis, the output currently on show will be re-calculated/rendered after every study, no matter how many there are. This is time consuming and not optimal. 

Suggest having a 'confirm' or 'update' button to press when the user has finalised which studies they want to exclude for a sensitivity analysis.

**Comment by nabury** [comment]
Agreed. I think it would be useful to have a general review of reactivity within the app (will also link well with reporting) to identify other similar issues. (i.e. linked to this, you could change the studies in the sensitivity analysis and not re-run the Bayesian analysis so have the two showing separate sets of results)

**Comment by nabury** [comment]
Discussed in meeting and decided to keep frequentist sensitivity analysis instantly reactive
