### ISSUE TITLE
Relative effects panel not displaying

### ISSUE THREAD

**Issue by nabury** [CRSU-Apps/MetaInsight#22]
The forest plot in the relative effects panel is not displaying on the hosted version of the app.  Downloads of the plot still work.

![3c](https://user-images.githubusercontent.com/98603626/228873069-12445845-df7e-4b08-b08d-bb7e489d8202.png)

**Comment by BalancedmonkeY** [comment]
I cannot recreate the issue - i.e. just now it's all working fine 

![image](https://user-images.githubusercontent.com/29865361/229503824-c7595aaf-9942-4d58-95d8-8e2bdd5c1a00.png)

@RyanJField Can you check whether it's working for you please?

It may have been shinyapps.io glitching that afternoon.

**Comment by RyanJField** [comment]
I have tried this afternoon on 3 different browsers on two computers and am unable to replicate.

![Screenshot 2023-04-03 135806](https://user-images.githubusercontent.com/57794045/229518652-ced935ff-f652-4722-bef0-f6e9b9c57ed4.png)

I suggest closing this issue, unless it reappears, in which case, we should take a look at the shinyapps.io logs to see if it is server side or browser side..
