### ISSUE TITLE
Add Branch Protection

### ISSUE THREAD

**Issue by RyanJField** [CRSU-Apps/MetaInsight#44]
Add branch protections rules to the main branch, require a pull request and at least 1 reviewer.

**Comment by RyanJField** [comment]
@CRSU-Apps/devs I have added branch protections rules, does anyone have any comments about the number of minimum reviewers, currently this is set to 1. This can be increased or we could have an informal rule stating don't merge unless all requested reviewers have approved the PR.

**Comment by nabury** [comment]
I think 1 reviewer as the minimum is fine - for small updates that's often all you need.

**Comment by JanionNevill** [comment]
Agreed. I think that 2 reviewers are only needed for big changes or where nobody has sufficient expertise in the area on their own.

**Comment by RyanJField** [comment]
Closing as agreement on 1 reviewer.
