### ISSUE TITLE
Better error messaging for wrong data type

### ISSUE THREAD

**Issue by BalancedmonkeY** [CRSU-Apps/MetaInsight#51]
Currently, if you're in the continuous set-up and try and load a binary data file, no errors are thrown up on the data upload tab, then when you go to analysis tab, it just gives the generic 'contact app author' message (and vice versa).

Would be good to have a pop-up message saying when a user has uploaded the wrong type of data.

**Comment by BalancedmonkeY** [comment]
Jira MI-13

**Comment by JanionNevill** [comment]
This has been resolved as of version 5.2.0
