### ISSUE TITLE
Download example data buttons not working

### ISSUE THREAD

**Issue by nabury** [CRSU-Apps/MetaInsight#61]
The download example dataset buttons in the 'load data' tab are not working for both binary and continuous data.

In addition, binary long format upload text should be changed to:
"The long format data file should contain the following columns" 
to match the continuous text

**Comment by nabury** [comment]
Created a branch for this issue - [hot fix-download_buttons ](https://github.com/CRSU-Apps/MetaInsight/tree/hotfix-download_buttons)

**Comment by BalancedmonkeY** [comment]
Can this issue now be closed?

**Comment by RyanJField** [comment]
Yes.
