### ISSUE TITLE
Improve process for user uploaded data

### ISSUE THREAD

**Issue by nabury** [CRSU-Apps/MetaInsight#9]
The current method for uploading data is not very flexible and is a common source of difficulty for new users. This applies for both the data and the treatment labels. Many of the common issues are recorded within the troubleshooting document.  

Edited to add - this issue would need to be broken down into a number of smaller issues to cover the ways in which uploading data could be made more flexible and producing error messages to catch common mistakes. Although non-essential, improvements would make MetaInsight more user friendly and should decrease the number of user emails we receive.

**Comment by JanionNevill** [comment]
From what I've seen, a useful improvement would be to make the error messages give information about what went wrong, rather than just stating that an error has occurred.

**Comment by JanionNevill** [comment]
@nabury Do you think that this issue can be closed now?
As of version 5.2.0 we have rio for flexible file types, data validation for column titles, and the various other upload improvements from last year.

**Comment by nabury** [comment]
> @nabury Do you think that this issue can be closed now? As of version 5.2.0 we have rio for flexible file types, data validation for column titles, and the various other upload improvements from last year.

Yes!
